-- Script generated by Redgate Compare v1.24.1.24210
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales_products.fk_sales...';END$$;
ALTER TABLE public.sales_products DROP CONSTRAINT fk_sales;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales_products.fk_product...';END$$;
ALTER TABLE public.sales_products DROP CONSTRAINT fk_product;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales.sales_client_id_fkey...';END$$;
ALTER TABLE public.sales DROP CONSTRAINT sales_client_id_fkey;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.products_code_key...';END$$;
ALTER TABLE public.products DROP CONSTRAINT products_code_key;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.clientes_code_key...';END$$;
ALTER TABLE public.clientes DROP CONSTRAINT clientes_code_key;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_products_sales_id_seq...';END$$;
ALTER SEQUENCE public.sales_products_sales_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_products_products_id_seq...';END$$;
ALTER SEQUENCE public.sales_products_products_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales_products...';END$$;
DROP TABLE public.sales_products;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales_products_sales_id_seq...';END$$;
DROP SEQUENCE public.sales_products_sales_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales_products_products_id_seq...';END$$;
DROP SEQUENCE public.sales_products_products_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_id_seq...';END$$;
ALTER SEQUENCE public.sales_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_client_id_seq...';END$$;
ALTER SEQUENCE public.sales_client_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales...';END$$;
DROP TABLE public.sales;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales_id_seq...';END$$;
DROP SEQUENCE public.sales_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.sales_client_id_seq...';END$$;
DROP SEQUENCE public.sales_client_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.products_id_seq...';END$$;
ALTER SEQUENCE public.products_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.products...';END$$;
DROP TABLE public.products;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.products_id_seq...';END$$;
DROP SEQUENCE public.products_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.clientes_id_seq...';END$$;
ALTER SEQUENCE public.clientes_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.clientes...';END$$;
DROP TABLE public.clientes;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.clientes_id_seq...';END$$;
DROP SEQUENCE public.clientes_id_seq;

SET check_function_bodies = true;
