-- Script generated by Redgate Compare v1.24.1.24210
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.clientes.newcolumn...';END$$;
ALTER TABLE public.clientes ADD COLUMN newcolumn integer;

SET check_function_bodies = true;
