-- Script generated by Redgate Compare v1.24.1.24210
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_products_sales_id_seq...';END$$;
CREATE SEQUENCE public.sales_products_sales_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.sales_products_sales_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_products_products_id_seq...';END$$;
CREATE SEQUENCE public.sales_products_products_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.sales_products_products_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_products...';END$$;
CREATE TABLE public.sales_products (
    sales_id integer NOT NULL DEFAULT nextval('public.sales_products_sales_id_seq'::regclass),
    products_id integer NOT NULL DEFAULT nextval('public.sales_products_products_id_seq'::regclass),
    price numeric(10,2),
    amount integer,
    sub_total numeric(10,2)
);
ALTER TABLE public.sales_products ADD CONSTRAINT sales_products_pkey PRIMARY KEY (sales_id, products_id);
ALTER TABLE public.sales_products OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_products_sales_id_seq...';END$$;
ALTER SEQUENCE public.sales_products_sales_id_seq OWNED BY public.sales_products.sales_id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_products_products_id_seq...';END$$;
ALTER SEQUENCE public.sales_products_products_id_seq OWNED BY public.sales_products.products_id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_id_seq...';END$$;
CREATE SEQUENCE public.sales_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.sales_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_client_id_seq...';END$$;
CREATE SEQUENCE public.sales_client_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.sales_client_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales...';END$$;
CREATE TABLE public.sales (
    id integer NOT NULL DEFAULT nextval('public.sales_id_seq'::regclass),
    client_id integer NOT NULL DEFAULT nextval('public.sales_client_id_seq'::regclass),
    total numeric(10,2)
);
ALTER TABLE public.sales ADD CONSTRAINT sales_pkey PRIMARY KEY (id);
ALTER TABLE public.sales OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_id_seq...';END$$;
ALTER SEQUENCE public.sales_id_seq OWNED BY public.sales.id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.sales_client_id_seq...';END$$;
ALTER SEQUENCE public.sales_client_id_seq OWNED BY public.sales.client_id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_products.fk_sales...';END$$;
ALTER TABLE public.sales_products ADD CONSTRAINT fk_sales FOREIGN KEY (sales_id) REFERENCES public.sales (id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.products_id_seq...';END$$;
CREATE SEQUENCE public.products_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.products_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.products...';END$$;
CREATE TABLE public.products (
    id integer NOT NULL DEFAULT nextval('public.products_id_seq'::regclass),
    code character varying(50),
    name character varying(100),
    price numeric(10,2)
);
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.products OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.products_id_seq...';END$$;
ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_products.fk_product...';END$$;
ALTER TABLE public.sales_products ADD CONSTRAINT fk_product FOREIGN KEY (products_id) REFERENCES public.products (id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.products_code_key...';END$$;
ALTER TABLE public.products ADD CONSTRAINT products_code_key UNIQUE (code);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.clientes_id_seq...';END$$;
CREATE SEQUENCE public.clientes_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.clientes_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.clientes...';END$$;
CREATE TABLE public.clientes (
    id integer NOT NULL DEFAULT nextval('public.clientes_id_seq'::regclass),
    code character varying(50),
    name character varying(100),
    cinit character varying(20),
    documenttype character varying(5),
    email character varying(100),
    newcolumn integer
);
ALTER TABLE public.clientes ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);
ALTER TABLE public.clientes OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.clientes_id_seq...';END$$;
ALTER SEQUENCE public.clientes_id_seq OWNED BY public.clientes.id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales.sales_client_id_fkey...';END$$;
ALTER TABLE public.sales ADD CONSTRAINT sales_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clientes (id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.clientes_code_key...';END$$;
ALTER TABLE public.clientes ADD CONSTRAINT clientes_code_key UNIQUE (code);

SET check_function_bodies = true;
