-- Script generated by Redgate Compare v1.24.1.24210
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.clientes.newcolumn...';END$$;
ALTER TABLE public.clientes DROP COLUMN newcolumn;

SET check_function_bodies = true;
